tree-sitter/tree-sitter-ruby

grammar.js
grammar_test/literals.txt
src/grammar.json

This reduces the size of the parser object file from about 14mb to about 9mb. It does allow comments and whitespace between `%q` and its delimiter, but I think it is ok in general to parse a superset of the language.
/cc @robrix

Make delimiters separate tokens from beginnings of '%' literals

---

grammar.js
grammar_test/comments.txt
grammar_test/control-flow.txt
grammar_test/declarations.txt
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json
src/tree_sitter/parser.h

Going to track work as I go to bring tree-sitter-ruby up-to-date and get the tests passing again. ~~~With a couple of fixes here and in tree-sitter, tests are currently passing, but generate times are very slow (on the order of 20mins).~~~ EDIT: Back to acceptable generate/build times.
cc @maxbrunsfeld

Bring ruby grammar up to date, green tests, faster generate/build

---

grammar.js
grammar_test/control-flow.txt
src/grammar.json

Some minor changes to the way we parse control flow blocks.
- Removed `then_block` production to rely on primary production instead (like `if_statement` or `begin_statement`, etc)
- Improved parsing of `rescue_block`:
- `s/do/then`
- Handle argument list to rescue multiple exception types.
- Production for capturing last exception into a local variable.
- Parse rescue modifiers (e.g. `foo rescue nil`). Fixes #13

Parsing improvements for control flow block

---

grammar.js
grammar_test/control-flow.txt
grammar_test/declarations.txt
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json

Don't produce `(last_exception (identifier))`, instead produce `(last_exception)` and tighten identifier pattern for allowed exception capture variable names.

Better handling of exception capture in rescue blocks

---

grammar.js
grammar_test/control-flow.txt
grammar_test/declarations.txt
grammar_test/expressions.txt
grammar_test/literals.txt
grammar_test/statements.txt
index.js
src/grammar.json

This allows parsing of:
Additionally, scope resolution, element reference, and member access all allow functions on their left hand side now.
This also bumps to latest tree-sitter with new precedence handling.

Singleton classes, block arguments, and bug fixes

---

grammar.js
grammar_test/control-flow.txt
grammar_test/declarations.txt
grammar_test/expressions.txt
grammar_test/literals.txt
grammar_test/statements.txt
src/grammar.json

~~Very much a WIP and I'm still planning to push additional commits.~~ Ready for review now.

Continue to expand ruby grammar

---

grammar.js
grammar_test/control-flow.txt
grammar_test/declarations.txt
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json

- Bring back the balanced delimiters for strings, regexes, symbols, and subshells.
- Hack fix to be able to parse things like `3.times` until we have a better backtrack mechanism in tree-sitter. The problem is that the float regex's `.` is capturing `3.`, but then fails and errors entirely when it finds a `t` next. Instead we need to be able to backtrack and try another option (like an `integer` in a `call`.
- Allow method names to have `=` on the end like `def foo=; end`
- Rename exception list and variable in rescues and relax the captured exception variable to be any `_lhs`.
- Fix for when trailing commas in argument lists are allowed (only when you're using `()` or `[]` around the argument list).
- Hack fix for rules that allow interpolation, but where just a single `#` character is …

Delimiters and other fixes

---

grammar.js
grammar_test/expressions.txt
src/grammar.json

Parse multiple assignments like `x, y = [1, 2]` ~~~and `x, * = 1, 2`.~~~ This is a first pass that only accepts multiple variables on the left hand side.

Parse multiple (left hand side) assignments

---

grammar.js
grammar_test/control-flow.txt
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json

This makes the parse table way smaller, avoiding the unsigned integer overflow problem.

Unify the many operator rules into 'binary' and 'unary'

---

grammar.js
grammar_test/declarations.txt
src/grammar.json

Parse Perl style BEGIN/END blocks like:
``` ruby
BEGIN {
puts "runs first"
}
END {
puts "runs last"
}
```

Parse BEGIN {} and END {} blocks

---

grammar.js
grammar_test/declarations.txt
src/grammar.json

Things like:
``` ruby
def foo
super.bar a, b
end
```
are failing b/c we don't treat `super` as a method call. This fixes that, by no longer having a rule specifically for `super` and instead relying on `method_call`. We could duplicate `method_call` and `call` parsing for super, but that doesn't seem worth it.

Parse super as a method

---

grammar.js
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json

Allowing parsing of array literals constructed with splat/rest arguments like:
``` ruby
a = [foo, *bar]
```
This also renames `s/rest_assignment/rest_argument` since it's used in multiple places now.

Handle parsing array literals with rest splat syntax

---

grammar.js
grammar_test/expressions.txt
src/grammar.json

Rest (splat) arguments in method calls were previously causing errors, this fixes that.
```ruby
foo(*bar)
```

Parse rest arguments in method calls

---

grammar.js
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json

There were previously two almost identical rules for pair (one used for constructing hash literals, and the other for method arguments). This collapses into a single pair rule with the more powerful ability to parse any valid `_arg` as the key in a pair. Valid ruby code like this was previously failing to parse:
```ruby
foo([] => 1)
foo(bar => 1)
```

Collapse up to one pair rule that allows any _arg as the key

---

grammar.js
src/grammar.json

Depends on https://github.com/tree-sitter/tree-sitter/pull/55 which allows us to use `\S`.
It's very possible that this regex can be further simplified. Here's some test data of valid character literals and a [good reference](https://ruby-doc.org/core-2.3.0/doc/syntax/literals_rdoc.html).
``` ruby
?a
?"a   # Should not match
?abc  # Should not match
?\n
?\\
?\u{41}
?\C-a
?\M-\C-a
?\C-\M-a
```

Use \S to cleanup char literal regex

---

grammar.js
package.json
src/grammar.json
src/scanner.cc
src/tree_sitter/parser.h

The latest tree-sitter features let us clean up the grammar a bit:
* We can distinguish between floats (`123.456`) from method calls on numbers (`123.to_s`) within the lexer by using backtracking, so we don't need a `conflict` between `float` and `call` (https://github.com/tree-sitter/tree-sitter/pull/68).
* Similarly, we can distinguish setter symbols (`:foo=`) from symbols followed by hash rockets (`:foo=>`) within the lexer, so we can tokenize symbols entirely in the external scanner, instead of having to fall back on the internal scanner.
* The external scanner needs to know if the `/` operator is valid. We can now specify that operator as an external directly using a string literal, instead of having to give it a name (https://github.com/tree-sitter/tree-sitter/pull/70). 
/cc @tclem

Upgrade tree-sitter to allow backtracking

---

src/scanner.cc

isalnum is only defined if the input is in the ASCII range. Nothing bad happens
on mac afaict but will cause an out-of-bounds read on Linux:
```
==11146== ERROR: libFuzzer: deadly signal
#0 0x649030 in fuzzer::Fuzzer::CrashCallback() /src/libfuzzer/FuzzerLoop.cpp:195:5
#1 0x648fd9 in fuzzer::Fuzzer::StaticCrashSignalCallback() /src/libfuzzer/FuzzerLoop.cpp:179:6
#2 0x7f118dd6638f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1138f)
#3 0x7f118d396d0d in isalnum (/lib/x86_64-linux-gnu/libc.so.6+0x2dd0d)
#4 0x42d44a in (anonymous namespace)::Scanner::scan_symbol_identifier(TSLexer*) /src/tree-sitter/tree-sitter-ruby/src/scanner.cc:250:12
#5 0x42be29 in (anonymous namespace)::Scanner::scan(TSLexer*, bool const*) /src/tree-sitter/tree-sitter-ruby/src/scanner.cc:727:18
#6 0x62eb83 in parser__lex …
```

Use wide-char version of ctype.h functions

---

grammar_test/single-cr-as-whitespace.rb
src/scanner.cc

Fixes https://github.com/tree-sitter/tree-sitter-ruby/issues/50

Treat single CR characters as whitespace, not as line breaks

---

corpus/expressions.txt
corpus/literals.txt
grammar.js
index.js
package.json
script/parse-examples
src/grammar.json
src/scanner.cc

Additional improvements to the ruby grammar

---

corpus/declarations.txt
grammar.js
src/grammar.json
src/scanner.cc

Fixes an issue with parsing the `<<` syntax used to extend the definition of a class singleton when there is no space between the `<<` and the class name.
``` ruby
class Foo
class <<self
end
end
```
The `<<self` was getting parsed as heredoc beginning and then later failing when there was no end. This fixes that.

Allow class <<self to parse

---

script/known_failures.txt
script/parse-examples

Takes some inspiration from @maxbrunsfeld script in [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash/blob/master/script/parse-examples.sh) to speed up example testing (really just a pass/fail smoke test).

Faster and more comprehensive example smoke testing

---

corpus/expressions.txt
corpus/literals.txt
grammar.js
script/known_failures.txt
src/grammar.json
src/scanner.cc

Takes over from https://github.com/tree-sitter/tree-sitter-ruby/pull/62 and allows us to parse things like:
``` ruby
some_method_call if: true
```
Thanks for the suggestion to detect this in the scanner @maxbrunsfeld - that worked pretty well and I spent some time making it so that we can just maintain a list of these and add/remove as there may be more reserved words I don't know about. I'd love a little review here as my C++ is a bit rusty.

Use external scanner to detect reserved identifiers used as keyword args

---

corpus/literals.txt
grammar.js
src/grammar.json
src/scanner.cc

Fix for heredocs that use a suffix `.` for method continuation like:
``` Ruby
joins(<<~SQL).
`foo`
SQL
where("a")
```
Based on #67

Heredoc method continuation fix

---

corpus/expressions.txt
grammar.js
src/grammar.json
src/scanner.cc

The new scanner code for identifier hash keys in #70 has a bug that breaks `/` and regex ambiguities because it consumes but doesn't return if a hash key is not found. This fixes that. 🎩 @maxbrunsfeld

Test and fix IDENTIFIER_HASH_KEY consuming and not returning

---

corpus/expressions.txt
grammar.js
package.json
src/grammar.json

For some reason, we had explicitly given the `hash` rule a higher precedence than `block`, even though the opposite is correct; `puts {}` parses as a call with an empty block, not an empty hash.
A adjusted several existing tests that had incorrect assertions and added one new test specifically about dot calls with blocks.
Fixes #74

Fix precedence of empty block vs empty hash

---

script/parse-examples

Gives us some basic stats on percentage of code that parses in particular example repositories.

Print stats about how many examples are successfully parsing

---

corpus/expressions.txt
corpus/literals.txt
grammar.js
package.json
src/grammar.json
src/scanner.cc
src/tree_sitter/parser.h

Depends on https://github.com/tree-sitter/tree-sitter/pull/183
When parsing multiple disjoint ranges of text, we now insert 'line break' tokens in between each range. This prevent parse errors when parsing ERB code like this.
```erb
<div id=<%= get_id %>><%= get_content %></div>
```
We've also changed the way string interpolations are parsed. There is now an explicit node for the `interpolation` itself, which contains the interpolated statement, as well as anonymous nodes for the `#{` and `}` delimiters. These things are important for syntax highlighting.
As a happy accident, the change that we made regarding interpolations resulted in a considerably smaller parse table. The binary size is now down to 6.6MB.
/cc @tclem and @robrix since this changes the shape of the parse trees.
🍐'd with …

Insert 'line break' tokens at included range boundaries

---

corpus/expressions.txt
corpus/literals.txt
grammar.js
src/grammar.json
src/scanner.cc

Fixes #6
Fixes #80
There are now distinct `string_array` and `symbol_array` nodes. Their children are `bare_string` and `bare_symbol` respectively.

Create separate nodes for bare words in string/symbol arrays

---

.travis.yml
appveyor.yml
package.json

This support is along the same lines as tree-sitter/node-tree-sitter#19 but with modifications to support the compiler settings + tree-sitter-cli tests
MacOS doesn't version clang the same way as Linux so I set it to a 9.x version of XCode running on 10.12

Add Prebuild support

---

corpus/expressions.txt
corpus/literals.txt
grammar.js
src/grammar.json
src/scanner.cc

This PR adds explicit syntax nodes for escape sequences within string, symbol, subshell, heredoc, and regex literals.

Parse escape sequences in literals

---

grammar.js
package.json
src/grammar.json
src/scanner.cc

This new API means we don't have to use the external scanner for tokens like `(`, `[`, `::`, and `:`, which sometimes have different meaning when not preceded by leading whitespace.
https://github.com/tree-sitter/tree-sitter/pull/190

Use immediate token API for preceding-whitespace-sensitive tokens

---

src/scanner.cc

`literal` is a reference to the last element so it is invalidated after we call
`literal.pop_back()`. Use a temporary so we don't use `literal` after it has
been popped:
```
==14==ERROR: AddressSanitizer: container-overflow on address 0x603000000160 at pc 0x00000051bfe2 bp 0x7ffca8ec7980 sp 0x7ffca8ec7978
READ of size 4 at 0x603000000160 thread T0
SCARINESS: 17 (4-byte-read-container-overflow)
#0 0x51bfe1 in (anonymous namespace)::Scanner::scan_literal_content(TSLexer*) /src/octofuzz/tree-sitter/test/fixtures/grammars/ruby/src/scanner.cc:669:25
#1 0x51884f in (anonymous namespace)::Scanner::scan(TSLexer*, bool const*) /src/octofuzz/tree-sitter/test/fixtures/grammars/ruby/src/scanner.cc:726:16
#2 0x66cda7 in ts_parser__lex /src/octofuzz/tree-sitter/src/runtime/parser.c:324:11
```

Avoid potential use-after-free in regex scanner

---

corpus/control-flow.txt
corpus/literals.txt
grammar.js
src/grammar.json

Refs https://github.com/atom/language-ruby/issues/237
Previously, specifying the folding behavior for `if`, `elsif`, and `rescue` blocks in Atom was pretty tricky. There wasn't an explicit node to differentiate the 'body' of these nodes from their condition, and from any nested `elsif` or `else` clauses.
Now, the body of these nodes is always wrapped in a `then` node, whether or not there is an explicit "then" token.
I also made a few other minor changes:
* Parse empty statements (redundant `;` tokens) correctly regardless of where they occur
* Remove a couple of wrapper nodes that increase the size of the parse tree unnecessarily: `_if_tail` and `_top_level_statement`.
/cc @tclem - This will affect Ruby assignment in your app, though I imagine it would simplify it, because it's much …

Use explicit `then` node to wrap statements inside if/case/rescue/when

---

.travis.yml
package.json

[node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter/blob/master/package.json#L30) is built against all ABI versions, we may want to do the something for languages otherwise we don't have rebuilds for pure Nodejs.

Prebuilt for Electron and Node

---

package.json

It looks like #108 removed Electron 3 from the list of prebuild targets, which seems to be causing problems with the `language-ruby` Atom package on Atom 1.39.1, which uses Electron 3. Locking the `language-ruby` dependency to `tree-sitter-ruby@0.15.0` makes the build pass on Travis, so I'm hopeful that adding  the 3.0 Electron target back resolves this. I'm not sure why we aren't successfully falling back to a manual build in this case.

Add Electron 3 back to the list of prebuild targets

---

package.json

The prebuild package has some security vulnerabilities, so
we better update it.
@maxbrunsfeld @dcreager

NPM: upgrade prebuild

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/declarations.txt
test/corpus/expressions.txt
test/corpus/line-endings.txt
test/corpus/literals.txt
test/corpus/single-cr-as-whitespace.rb

The contents of string literals and heredocs used to be hidden because the rule names for them start with an `_`.
@dcreager

Make string content and heredoc content visible

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expressions.txt

Having named fields should be nicer to work with, instead of having to know the order of the child nodes.
I was trying to imitate the way binary operators are handled; hopefully I haven't broken anything.

Add fields for unary operators

---

grammar.js
src/grammar.json
src/node-types.json

This fixes the `pattern` field of the `when` rule. Having the field defined outside the `commaSep` call causes the commas to be treated as patterns too.
@maxbrunsfeld

Correct field for when.pattern

---

src/scanner.cc
test/corpus/expressions.txt

This fixes https://github.com/tree-sitter/tree-sitter-ruby/issues/136
Original bug report for our application: https://github.com/returntocorp/semgrep/issues/2157

Fix range of characters supported in keyword argument

---

grammar.js
queries/highlights.scm
queries/tags.scm
src/grammar.json
src/node-types.json
test/corpus/control-flow.txt
test/corpus/declarations.txt
test/corpus/expressions.txt
test/corpus/line-endings.txt
test/corpus/literals.txt
test/corpus/single-cr-as-whitespace.rb
test/corpus/statements.txt

For example, given the following two expressions, the resulting parse trees are much more similar now.
```ruby
foo.bar
foo.bar()
```
Before these changes:
```bash
(program [0, 0] - [2, 0]
(call [0, 0] - [0, 7]
receiver: (identifier [0, 0] - [0, 3])
method: (identifier [0, 4] - [0, 7]))
(method_call [1, 0] - [1, 9]
method: (call [1, 0] - [1, 7]
receiver: (identifier [1, 0] - [1, 3])
method: (identifier [1, 4] - [1, 7]))
arguments: (argument_list [1, 7] - [1, 9])))
```
After these changes:
```bash
(program [0, 0] - [2, 0]
(call [0, 0] - [0, 7]
receiver: (identifier [0, 0] - [0, 3])
method: (identifier [0, 4] - [0, 7]))
(call [1, 0] - [1, 9]
receiver: (identifier [1, 0] - [1, 3])
method: (identifier [1, 4] - [1, 7])
arguments: (argument_list [1, 7] - [1, 9])))
```
I noticed while making …

Unify call and method_call

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/control-flow.txt

Trailing commas (accepted by MRI) no longer cause parser errors, e.g. in:
```rb
for x, in 1..10 do
puts x
end
```
For the following example, with multiple identifiers *not* surrounded by parentheses, it was awkward (for my needs, anyway) to have multiple pattern nodes without an overall node for the entire `key, value` pattern. Now, there is one.
```rb
for key, value in my_hash do
end
```

for-loop pattern improvements

---

grammar.js
src/grammar.json
src/scanner.cc
test/corpus/expressions.txt

```rb
foo **bar, baz
```
This example (now added as a test case) was being incorrectly parsed as a binary `**` operation, followed by some junk, causing errors:
```
(program [0, 0] - [1, 0]
(binary [0, 0] - [0, 9]
left: (identifier [0, 0] - [0, 3])
right: (identifier [0, 6] - [0, 9]))
(ERROR [0, 9] - [0, 14]
(identifier [0, 11] - [0, 14])))
```
I mirrored the way regular splat arguments are handled, and now it parses correctly:
```
(program [0, 0] - [1, 0]
(call [0, 0] - [0, 14]
method: (identifier [0, 0] - [0, 3])
arguments: (argument_list [0, 4] - [0, 14]
(hash_splat_argument [0, 4] - [0, 9]
(identifier [0, 6] - [0, 9]))
(identifier [0, 11] - [0, 14]))))
```

Fix error parsing hash splat arg followed by another arg

---

grammar.js
queries/highlights.scm
src/grammar.json
src/node-types.json
src/scanner.cc
test/corpus/declarations.txt
test/corpus/expressions.txt
test/corpus/literals.txt
test/corpus/statements.txt

I hope this change isn't too disruptive for anyone else, but it solves some issues we had with the current setup for symbols:
* since we treat leaf nodes specially for our use case, having `_simple_symbol` aliased to `symbol` meant that we couldn't handle it appropriately, since it appeared to be a non-leaf node in `node-types.json`.
* `_simple_symbol` nodes include the leading colon in the range (e.g. `:foo`), while `_identifier_hash_key` obviously don't have a leading colon (e.g. in `{ foo: 0 }` you get `foo`), so having them aliased to the same type made it difficult to get the symbol text/name in a consistent way.
Now there are four distinct node types that can represent symbols:
1. `bare_symbol` (unchanged; e.g. in `%i(foo bar baz)` symbol arrays)
2. `identifier_hash_key_symbol` …

Separate symbol aliases into distinct types

---

grammar.js
src/grammar.json
test/corpus/literals.txt

Per irb:
irb(main):016:0> ?\xff
=> "\xFF"
irb(main):017:0> ?\u{024f}
=> "ɏ"
irb(main):018:0> ?\u024f
=> "ɏ"
Add these test cases and update the character matching regex to enable.
Fixes tree-sitter/tree-sitter-ruby#145.

Add support for hex character literals

---

src/scanner.cc
test/corpus/literals.txt

This commit updates the lexer to specifically match the symbol :!~.
I also add test cases from
https://github.com/ruby/spec/blob/master/language/symbol_spec.rb:
- :_
- :!~
- :''
Fixes tree-sitter/tree-sitter-ruby#143.

Support :!~ symbols, add symbol test cases

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/declarations.txt

This makes `node-types.json` a little more precise - now the generic children of `class` are just the body statements.

Make superclass a field

---

src/scanner.cc
test/corpus/expressions.txt

@nickrolfe I think this should fix the parse error on
```ruby
foo
.bar
```

Allow expression to continue after a line-comment

---

grammar.js
src/grammar.json
src/node-types.json

This improves the `node-types.json` output so we can handle beginless/endless ranges properly and distinguish inclusive and exclusive ranges.

Add field names to `range`

---

grammar.js
src/grammar.json
src/scanner.cc
test/corpus/errors.txt

This is a bit more subtle than the previous fixes in https://github.com/tree-sitter/tree-sitter-ruby/pull/188
The [ruby error_corpus test](https://github.com/tree-sitter/tree-sitter/blob/master/test/fixtures/error_corpus/ruby_errors.txt) was failing in the main repo on Windows, generating a slightly different error-corrected parse tree. I suspect this is because of the additional `\r` characters consumed by the external scanner which led the parser to prefer one GLR branch over another. I changed the external scanner so its behavior matches as closely as possible in both cases by doing a line-by-line diff of the debug parse output. If I had to summarize the changes, they would be "treat a standalone `\r` as a newline, unless it's directly followed by a `\n`, in which case consume `\r\n` …

Fix CRLF behavior mismatch during error recovery

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/patterns.txt

I forgot about the parenthesized patterns such as
```
case x
in (1..10) then ...
...
```
Checklist:

Add parenthesized_pattern

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/declarations.txt
test/corpus/expressions.txt
test/corpus/literals.txt
test/corpus/patterns.txt

This pull-request Implements the following items taken from https://rubyreferences.github.io/rubychanges/3.1.html
* Values in Hash literals and keyword arguments can be omitted
* Anonymous block argument
* Expressions and non-local variables allowed in pin operator `^`
The following items are *not* addressed by this pull request as did not yet find a good way to implement them without causing all sorts of grammar conflicts.
* One-line pattern matching (both versions) is no longer experimental
* Inside “endless” method definitions, method calls without parenthesis are allowed
Checklist:

Ruby 3.1 features

---

.github/workflows/ci.yml

This follows the change from https://github.com/tree-sitter/tree-sitter-java/pull/106 to try to get CI for windows working again. Thanks so much for the pointer!

Update to Node 16

---

grammar.js
script/known_failures.txt
script/parse-examples
src/grammar.json
src/node-types.json
src/scanner.cc
test/corpus/comments.txt
test/corpus/control-flow.txt
test/corpus/expressions.txt
test/corpus/literals.txt
test/corpus/patterns.txt
test/highlight/literals.rb

This PR includes various improvements to the parser. It is best reviewed on a commit-by-commit basis.
Checklist:
@nickrolfe

Parser improvements

---

.github/workflows/ci.yml

@maxbrunsfeld This PR fixes the CI failures on windows but running the jobs on windows-2019. 
See also: https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/
I think a better fix would be to upgrade node-gyp upstream to a version that works with Visual Studio 2022, but this should work for now.
Checklist:

CI: use windows-2019 for now

---

grammar.js
src/grammar.json
src/node-types.json
src/tree_sitter/parser.h

Having named operators helps the CodeQL dbscheme generator to produce better output.
Checklist:

Add named rules for the various call operators

---

Cargo.toml

The other grammars allow both .19 and .20.

Allow newer tree-sitter upstream library.

---

Cargo.toml
package.json

Bump tree-sitter version to 0.20

---

grammar.js
src/grammar.json
test/corpus/expressions.txt

Fix parse error in 'foo! if condition'

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/declarations.txt
test/corpus/expressions.txt
test/corpus/literals.txt
test/corpus/patterns.txt

A majority of other languages I noticed wrap class and function bodies in their own named node that can be easily queried(checked javascript, Lua, java, etc). Without this named node it makes targeting the contents of these structures difficult, cumbersome, and realllyyyy slow.  
Checklist:

Wrap class, module, method, and block bodies in a named node

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/declarations.txt

#224 added a `body` field for method bodies. However, we forgot about `end`-less methods., such as:
```
def foo = bar
def Object.foo = bar
```
As a result their bodies are still represented as unnamed children. 
@npezza93 @maxbrunsfeld 
Checklist:

Add body field for end-less methods

---

grammar.js

Fixes #228. `arguments` is a reserved word in JavaScript and throws errors in many parsers.
Checklist:

fix: rename reserved word “arguments”

---

Cargo.toml
bindings/rust/README.md

Allow a range of tree-sitter in dependencies. (Akin to tree-sitter-go)

Bump versions

---

grammar.js
package.json
src/grammar.json
src/node-types.json
test/corpus/expressions.txt

From [Ruby 3.2 release notes](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)
> Anonymous rest and keyword rest arguments can now be passed as arguments, instead of just used in method parameters. [[Feature #18351](https://bugs.ruby-lang.org/issues/18351)]
> ```ruby
>  def foo(*)
>    bar(*)
>  end
>  def baz(**)
>    quux(**)
>  end
>```
This PR also upgrade the node-gyp version to solve a CI failure on the latest version of OSX: https://github.com/tree-sitter/tree-sitter-ruby/actions/runs/3873495109/jobs/6603577164
Checklist:

Anonymous (hash) splat arguments

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/patterns.txt

This pull request adds the one-line pattern matching syntax (`expr in pattern` and `expr => pattern`). 
Checklist:

One-line pattern matching

---

src/scanner.cc
test/corpus/expressions.txt

My earlier changes https://github.com/tree-sitter/tree-sitter-ruby/pull/238 somehow caused the parser to hang on some inputs. I'm not sure how it ended up in an infinite loop, but the changes I made to the scanner were not entirely right. I changed the scanner to `return false` if it sees a newline before a `.` character that has no following `.` character otherwise we'd end up calling `mark_end`, `advancing` a bit, and subsequently trying to scan a next token which makes no sense. 
@hendrikvanantwerpen 
Checklist:

Fix non-termination in parser

---

package.json
src/scanner.cc
test/corpus/expressions.txt

This should improve parsing of expressions with a division (`/`) operator before a line break. Previously the scanner treated those as the start of a regular expression literal (`/..../`).
For example:
```ruby
foo /
5
```
Checklist:

Fix scanning of division vs regex before line ending

---

grammar.js
src/grammar.json
test/corpus/control-flow.txt

This PR fixes syntax errors in `case` statements with a newline before its value expression. For example
```ruby
case
foo
when ....
end
```
Checklist:

Fix 'case' with newlines before expression

---

grammar.js
src/grammar.json
test/corpus/literals.txt

Reintroduces a whitespace that was removed on https://github.com/tree-sitter/tree-sitter-ruby/pull/252/files#diff-919ac210accac9ecc55a76d10a7590e3d85ca3f0e165b52d30f08faee486d0cbR1170.

Fix parsing of multiple unicode escapes

---

grammar.js
src/grammar.json
test/corpus/comments.txt

Reverts a change made on https://github.com/tree-sitter/tree-sitter-ruby/pull/255, cc @amaanq .

Do not require newline after block comment `=end`
