tree-sitter/tree-sitter-ruby

grammar.js
grammar_test/control-flow.txt
grammar_test/declarations.txt
grammar_test/expressions.txt
grammar_test/literals.txt
src/grammar.json

Building on #20, this adds support for keyword parameters and arguments.
Fixes #10 as well.

Keyword parameters and arguments

---

grammar.js
grammar_test/declarations.txt
src/grammar.json

Continuing work on keyword parameters and arguments.

New production names for keyword parameters

---

grammar.js
src/grammar.json

Pair down conflicts section a little bit. cc @maxbrunsfeld

Give argument_lists lower prec to reduce conflicts

---

grammar.js
grammar_test/expressions.txt
src/grammar.json
src/tree_sitter/parser.h

Parse blocks as arguments. Updates to latest tree-sitter as well.

Parse do/end and {} block arguments

---

grammar.js
grammar_test/declarations.txt
src/grammar.json

Improve class and module trees to better represent their structure.

Improve class and module trees

---

grammar.js
grammar_test/expressions.txt
src/grammar.json

Allow parsing of multiple right hand sides in assignment.

Basic parsing of multiple right hand sides in assignment

---

grammar.js
grammar_test/expressions.txt
src/grammar.json

Adds a few interesting assignment operators that were missing.

Parse a few more assignment operators

---

grammar.js
grammar_test/declarations.txt
src/grammar.json

Give specific structure to singleton methods

---

src/scanner.cc

Fixes the weird static linkage conflict issue we were seeing in Mac builds.

Namespace the scanner.

---

src/scanner.cc

Keeps scanner to C++98 features if we can.

Don't use range based for loop

---

corpus/literals.txt
grammar.js
src/grammar.json

Same as https://github.com/tree-sitter/tree-sitter-ruby/pull/68, but with master as the base.

Heredoc method continuation fix try 2

---

corpus/expressions.txt
src/scanner.cc

Fix up lexing binary/unary minus

---

package.json
src/binding.cc
src/node-types.json
src/tree_sitter/parser.h

https://github.com/lgeiger/node-abi/blob/master/index.js#L71
https://github.com/rubyide/vscode-ruby/issues/486

package.json: expand to include electron 4.0.4

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/literals.txt

Depends on https://github.com/tree-sitter/tree-sitter/pull/469

Model heredoc bodies using non-terminal extras

---

queries/highlights.scm
test/highlight/constants.rb

Fix some syntax highlighting issues with constants

---

queries/tags.scm

Goes with https://github.com/tree-sitter/tree-sitter/pull/648 as I'm iterating on the tree-sitter tag functionality.

Identify modules and singleton classes when tagging

---

grammar.js
src/grammar.json
src/node-types.json

An else-expression does not have a condition
@dcreager @maxbrunsfeld

Remove 'condition' field from 'else'

---

grammar.js
src/grammar.json
test/corpus/control-flow.txt

Allow case without linebreak

---

grammar.js
src/grammar.json
src/node-types.json

A small quality of life improvement.

Give setter identifier a field name

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/literals.txt

Allow interpolation to be empty

---

.github/workflows/ci.yml
grammar.js
src/grammar.json
src/scanner.cc
src/tree_sitter/parser.h

Fixes https://github.com/tree-sitter/tree-sitter-ruby/issues/164

Fixed CRLF behavior for tests

---

grammar.js
src/grammar.json
src/node-types.json
test/corpus/expressions.txt

```rb
foo[:bar] do |baz|
end
```

Handle element references with blocks

---

Package.swift

fix(swift): include scanner.c
